
import React from 'react';
import { SpinnerIcon, ZoomInIcon, DownloadIcon, ShareIcon, CompareIcon, RetryIcon } from './icons';
import type { GeneratedImage } from '../types';

interface ImageCardProps {
  image: GeneratedImage;
  onZoom: (url: string) => void;
  onCompare: () => void;
  onRetry: () => void;
}

const ImageCard: React.FC<ImageCardProps> = ({ image, onZoom, onCompare, onRetry }) => {
  const { title, src: imageUrl, isLoading, error } = image;

  const handleDownload = () => {
    if (!imageUrl) return;
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = `${title.replace(/\s+/g, '-')}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleShare = async () => {
    if (!imageUrl) return;

    if (!navigator.share) {
      alert("Sharing is not supported on your browser.");
      return;
    }

    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const file = new File([blob], `${title.replace(/\s+/g, '-')}.png`, { type: blob.type });

      await navigator.share({
        title: `AI Image: ${title}`,
        text: 'Generated by Past to the Future AI.',
        files: [file],
      });
    } catch (error) {
      console.error('Error sharing image:', error);
    }
  };

  return (
    <div className="bg-gray-800 rounded-lg shadow-lg overflow-hidden flex flex-col transform hover:scale-105 transition-transform duration-300">
      <div 
        className={`relative aspect-square w-full bg-gray-900 flex items-center justify-center ${imageUrl && !isLoading ? 'cursor-pointer' : ''}`}
        onClick={() => imageUrl && !isLoading && onZoom(imageUrl)}
        title={imageUrl && !isLoading ? 'Click to zoom' : ''}
      >
        {isLoading && (
          <div className="absolute inset-0 flex items-center justify-center">
            <SpinnerIcon className="w-12 h-12 text-indigo-500" />
          </div>
        )}
        {imageUrl && !isLoading && (
          <img src={imageUrl} alt={title} className="w-full h-full object-cover" />
        )}
        {error && !isLoading && (
            <div className="text-red-400 text-center p-4 flex flex-col items-center gap-4">
                <p className="font-semibold">Generation Failed</p>
                <p className="text-xs text-gray-400">{error}</p>
                 <button onClick={onRetry} className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white font-semibold rounded-md hover:bg-indigo-700 transition-colors">
                    <RetryIcon className="w-5 h-5" />
                    Retry
                </button>
            </div>
        )}
      </div>
      <div className="p-4 flex-grow flex flex-col justify-between">
        <h3 className="font-bold text-lg text-white mb-3">{title}</h3>
        <div className="flex items-center justify-end space-x-2">
           <button 
            onClick={onCompare} 
            disabled={!imageUrl}
            className="p-2 rounded-full bg-gray-700 hover:bg-indigo-600 disabled:bg-gray-800 disabled:text-gray-600 disabled:cursor-not-allowed text-white transition-colors"
            title="Compare"
          >
            <CompareIcon className="w-5 h-5" />
          </button>
          <button 
            onClick={() => imageUrl && onZoom(imageUrl)} 
            disabled={!imageUrl}
            className="p-2 rounded-full bg-gray-700 hover:bg-indigo-600 disabled:bg-gray-800 disabled:text-gray-600 disabled:cursor-not-allowed text-white transition-colors"
            title="Zoom In"
          >
            <ZoomInIcon className="w-5 h-5" />
          </button>
          <button 
            onClick={handleDownload}
            disabled={!imageUrl}
            className="p-2 rounded-full bg-gray-700 hover:bg-indigo-600 disabled:bg-gray-800 disabled:text-gray-600 disabled:cursor-not-allowed text-white transition-colors"
            title="Download"
          >
            <DownloadIcon className="w-5 h-5" />
          </button>
          <button 
            onClick={handleShare}
            disabled={!imageUrl || typeof navigator.share === 'undefined'}
            className="p-2 rounded-full bg-gray-700 hover:bg-indigo-600 disabled:bg-gray-800 disabled:text-gray-600 disabled:cursor-not-allowed text-white transition-colors"
            title="Share"
          >
            <ShareIcon className="w-5 h-5" />
          </button>
        </div>
      </div>
    </div>
  );
};

export default ImageCard;