
import React, { useState } from 'react';
import { SpinnerIcon, ZoomInIcon, DownloadIcon, ShareIcon, CompareIcon } from './icons';
import ComparisonSlider from './ComparisonSlider';

interface ImageCardProps {
  title: string;
  imageUrl: string | null;
  originalImageUrl?: string;
  isLoading: boolean;
  onZoom: (url: string) => void;
}

const ImageCard: React.FC<ImageCardProps> = ({ title, imageUrl, originalImageUrl, isLoading, onZoom }) => {
  const [isComparing, setIsComparing] = useState(false);

  const handleDownload = () => {
    if (!imageUrl) return;
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = `${title.replace(/\s+/g, '-')}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleShare = async () => {
    if (!imageUrl) return;

    if (!navigator.share) {
      alert("Sharing is not supported on your browser.");
      return;
    }

    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const file = new File([blob], `${title.replace(/\s+/g, '-')}.png`, { type: blob.type });

      await navigator.share({
        title: `AI Image: ${title}`,
        text: 'Generated by Past to the Future AI.',
        files: [file],
      });
    } catch (error) {
      console.error('Error sharing image:', error);
    }
  };

  return (
    <div className="bg-gray-800 rounded-lg shadow-lg overflow-hidden flex flex-col transform hover:scale-[1.02] transition-transform duration-300">
      <div className="relative aspect-square w-full bg-gray-900 flex items-center justify-center group">
        {isLoading && (
          <div className="absolute inset-0 flex items-center justify-center z-20">
            <SpinnerIcon className="w-12 h-12 text-indigo-500" />
          </div>
        )}
        
        {/* Toggle Compare Button (Only if we have both images and not loading) */}
        {!isLoading && imageUrl && originalImageUrl && (
            <button 
                onClick={() => setIsComparing(!isComparing)}
                className={`absolute top-3 right-3 z-30 p-2 rounded-full bg-black/60 hover:bg-indigo-600 text-white backdrop-blur-sm transition-all ${isComparing ? 'bg-indigo-600' : ''}`}
                title="Compare with Original"
            >
                <CompareIcon className="w-5 h-5" />
            </button>
        )}

        <div className="w-full h-full relative">
             {imageUrl ? (
                isComparing && originalImageUrl ? (
                    <ComparisonSlider originalImage={originalImageUrl} generatedImage={imageUrl} />
                ) : (
                    <img src={imageUrl} alt={title} className="w-full h-full object-cover" />
                )
            ) : (
                !isLoading && (
                    <div className="text-gray-500 text-center p-4 flex items-center justify-center h-full">
                        <p>Failed to generate.</p>
                    </div>
                )
            )}
        </div>

      </div>
      <div className="p-4 flex-grow flex flex-col justify-between border-t border-gray-700">
        <h3 className="font-bold text-lg text-white mb-3">{title}</h3>
        <div className="flex items-center justify-end space-x-2">
          <button 
            onClick={() => imageUrl && onZoom(imageUrl)} 
            disabled={!imageUrl}
            className="p-2 rounded-full bg-gray-700 hover:bg-indigo-600 disabled:bg-gray-800 disabled:text-gray-600 disabled:cursor-not-allowed text-white transition-colors"
            title="Zoom In"
          >
            <ZoomInIcon className="w-5 h-5" />
          </button>
          <button 
            onClick={handleDownload}
            disabled={!imageUrl}
            className="p-2 rounded-full bg-gray-700 hover:bg-indigo-600 disabled:bg-gray-800 disabled:text-gray-600 disabled:cursor-not-allowed text-white transition-colors"
            title="Download"
          >
            <DownloadIcon className="w-5 h-5" />
          </button>
          <button 
            onClick={handleShare}
            disabled={!imageUrl || typeof navigator.share === 'undefined'}
            className="p-2 rounded-full bg-gray-700 hover:bg-indigo-600 disabled:bg-gray-800 disabled:text-gray-600 disabled:cursor-not-allowed text-white transition-colors"
            title="Share"
          >
            <ShareIcon className="w-5 h-5" />
          </button>
        </div>
      </div>
    </div>
  );
};

export default ImageCard;
